Record Desktop Audio
elan-ev/opencast-studio pull request #1079
Opened 2023-08-30 10:53 UTC by narickmann

This PR allows Studio to record desktop audio and resolves #551

Unfortunately, not all browsers are supported yet, as you can see [here](https://caniuse.com/mdn-api_mediadevices_getdisplaymedia_audio_capture_support) and as Lukas mentioned here: [#551](https://github.com/elan-ev/opencast-studio/issues/551)

The users get a hint after selecting display as source, with which browsers they can record desktop audio.

Output of the recordings for download:

**Only camera recorded:** Nothing changed, the finished camera video will contain microphone audio (if recorded)

**Only display recorded:** If the user recorded both, desktop audio and microphone audio, the finished video will have both audio tracks.

**Display and camera recorded:** The finished desktop video will contain desktop audio and the finished camera video will contain the microphone audio

**One thing/problem:**
In the "Review & trim" step (also after uploading to Opencast), if both the display AND the camera were recorded: you only hear the microphone audio or nothing (depending on whether microphone audio was recorded or not). I'm not entirely sure why.
The audio is correct and audible for each of the videos that can be downloaded in the last step in Studio.

2023-08-31 20:55 UTC, lkiesow commented
> Only display recorded: If the user recorded both, desktop audio and microphone audio, the finished video will have both audio tracks.

Does this mean the resulting media container will have two audio streams? Or is it one stream with a mix of both audio sources?

2023-09-12 10:00 UTC, narickmann commented
> Does this mean the resulting media container will have two audio streams? Or is it one stream with a mix of both audio sources?

The resulting file contains one stream with a mix of both audio sources.

2023-09-14 10:37 UTC, lkiesow commented
Okay, that's definitely better than the alternative having two audio streams in one container.

Still, while this might be a bit more “professional”, I think it may cause some trouble, and it may be easier to just have a mix of all audio streams in all video containers. The current patch failing to play back audio correctly right now is a good example. For further processing, you now also need to make sure in some cases to mix audio afterward. It would be so much easier to just have the same audio everywhere.

2023-09-14 10:42 UTC, lkiesow commented on src/i18n/locales/en.json
> +  "no-desktop-audio-info": "Desktop audio is not recorded. \n If you want to record desktop audio, please use one of the following browsers: \n - Google Chrome, Edge and Opera: On Windows, the entire
> but on Linux and macOS only the audio of a tab can be captured.

I'm not quite sure what this means. What will be recorded?

> Internet Explorer 

I wouldn't add obscure and obsolete browsers to this list.

> Firefox […] do not support recording desktop audio.

Not true. Firefox lets you select all video sources. That includes monitor sources. It's just that the implementation would need to be slightly different.

2023-09-14 11:02 UTC, LukasKalbertodt commented
> **One thing/problem:**
> In the "Review & trim" step (also after uploading to Opencast), if both the display AND the camera were recorded: you only hear the microphone audio or nothing (depending on whether microphone audio was recorded or not). I'm not entirely sure why.
> The audio is correct and audible for each of the videos that can be downloaded in the last step in Studio.

https://github.com/elan-ev/opencast-studio/blob/3621089a3c9eaa08d54a529e12b5a65f18b2f8fb/src/steps/review/preview.tsx#L128-L132

So: you can just remove that (or make it conditional).

---

Currently, CI fails and there is no test deployment. Can you fix the issues and push again? There are also style lints that are visible here on GitHub.

---

> It would be so much easier to just have the same audio everywhere.

I'm unsure about that. I do have remind myself of the target audience of Studio, yes, you are right. I have one specific situation where separate audio streams are useful: if a user recorded a long session and only notices in the end that the microphone is way louder (or quieter) than the desktop audio. To make a useful video out of that, one would have to boost on of these tracks. With both tracks already combined that's basically impossible. Yes, this boosting would have to happen outside of Studio but at least it's possible.

One idea that was floating around in our chat: add both. The first audio track of both files is the "all sources combined" audio. And then we still add a second audio track that only has desktop audio or microphone. Players default to playing the first audio stream, so normal users wouldn't notice it. Sure, the file size would be slightly larger and the recording would require slightly more resources.

Dunno, I guess I don't have a strong opinion :shrug:

2023-11-16 12:39 UTC, JulianKniephoff commented
Rebased and fixed conflicts.

2023-11-16 12:53 UTC, JulianKniephoff commented
There is a test deployment now, but the code is subject to change, still. FWIW: https://test.studio.opencast.org/2023-11-16_12-41-36-pr1079-6890854908/

> In the "Review & trim" step (also after uploading to Opencast), if both the display AND the camera were recorded: you only hear the microphone audio or nothing (depending on whether microphone audio was recorded or not). I'm not entirely sure why.

For the record: This I can't confirm. Is this a platform issue? Can others reproduce this?

2023-11-20 09:47 UTC, JulianKniephoff commented
OK that bug should be fixed now, and I had to change a few other things, but this should work: All the audio tracks are now mixed and added as single audio track to all the resulting videos.

2023-11-20 14:31 UTC, LukasKalbertodt requested changes
Only small stuff. Otherwise this looks good. Will test the deployment now.

2023-11-20 14:31 UTC, LukasKalbertodt commented on src/steps/video-setup/preview.tsx
> +        </Trans>}
```suggestion
        tooltip={
            <Trans i18nKey={
              `steps.video.${hasAudio ? "display-audio-shared" : "display-audio-not-shared"}`
            }>
              <strong>Note:</strong> Explanation.
            </Trans>
        }
```

That fits the existing code style better.

2023-11-20 14:31 UTC, LukasKalbertodt commented on src/steps/video-setup/preview.tsx
> +        placement="bottom"
I think `top` would be better in this situation?

2023-11-20 14:31 UTC, LukasKalbertodt commented on src/steps/video-setup/preview.tsx
> +      whiteSpace: "pre-line",
I think this can be removed. And then the whole `css` attr can be one line presumably

2023-11-20 14:31 UTC, LukasKalbertodt commented on src/steps/video-setup/preview.tsx
> +        }}>
One line?

2023-11-20 14:43 UTC, LukasKalbertodt approved these changes
Everything looks good! I think I now tested every possible combination of video-source and microphone and seems like the output files are exactly as expected. 

We both noticed that the audio indicator UI can be fairly hidden, depending on what was shared. But that's the same for the settings button, so we will fix that later.

2023-11-20 14:46 UTC, merged