Updated README.md
elan-ev/opencast-studio pull request #946
Opened 2022-06-20 11:01 UTC by naweidner

Added section on how to release Opencast Studio

2022-07-05 15:04 UTC, lkiesow requested changes

2022-07-05 15:04 UTC, lkiesow commented on README.md
> +As release title enter the current date again in the same format.
```suggestion
As a release title, enter the current date again in the same format.
```

2022-07-05 15:04 UTC, lkiesow commented on README.md
> +### Update Opencast:
```suggestion
### Update Opencast
```

2022-07-05 15:04 UTC, lkiesow commented on README.md
> + Open a new PR (optional: add link to release and changelog in description)
```suggestion
 Open a new pull request (optional: add a link to the release and changelog in the description)
```

2022-07-05 15:04 UTC, lkiesow commented on README.md
> + Befor opening an new PR, you can build Opencast and test Opencast Studio (The release date should be on the info info page)
```suggestion
Before opening a new pull request, you can build Opencast and test Opencast Studio. The release date should be on the info page.
```

2022-08-01 07:35 UTC, LukasKalbertodt requested changes

2022-08-01 07:35 UTC, LukasKalbertodt commented on README.md
> +Go to modules/studio/pom.xml. You have to change two lines:
```suggestion
Go to `modules/studio/pom.xml`. You have to change two lines:
```

2022-08-01 07:36 UTC, LukasKalbertodt commented
I was so bold as to resolve all Lars' comments as they were fixed exactly as requested. I also added one suggestion and immediately committed it via GitHub, so this is now mergable!

2022-08-01 07:37 UTC, merged